name: vex-dev/sdk
on:
  push:
    branches: 
      - main
      - ci-*

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      sdk: ${{ steps.filter.outputs.sdk }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          sdk:
            - 'package.json'

  build_and_push:
    needs: [changes]
    if: needs.changes.outputs.sdk == 'true'
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@vex.dev'

      - run: npm ci

      - name: Publish package on NPM 📦
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ORG_TOKEN }}
        run: npm publish
